services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5434:5432"